flavor_text_damage = [
    "A console on the bridge explodes and kills a guy.",
    "Circus Bay destroyed, all clowns were killed.",
    "Septic Tank leak on deck 2.",
    "Chief Engineer is panicking and throwing stuff.",
    "Holoporn Theater destroyed.",
    "Zoo damaged, animals escaping.",
    "Ship Counselor reports that letting ship take damage is bad for crew morale, suggests not doing that.",
    "Bridge crew starts shaking violently.",
    "Lights flickering, explosion noises, etc...",
    "Captain's Quarters destroyed and you are now homeless.",
    "The Tachyon Chrono-Matrix has been destroyed but it moves backwards in time so it's fine because it never existed and we have a different one.",
    "Your pet Lionfish is panicking!",
    "Flux Capacitor destroyed.",
    "Ship's Caffeteria Destroyed.",
    "Chief Engineer's Rum Stash Destroyed.",
    "Captain's Self-Esteem Damaged.",
    "Ship's Android malfunctioning, we had to put him down.",
    "First Officer's Sex Dungeon Destroyed.",
    "Hair Salon Destroyed",
    "Chapel Destroyed.  God not responding.",
    "Baseball Field Destroyed.",
    "Gym Destroyed.  Cancelling Membership... FAILED.",
    "Ten Forward Destroyed.  Recreation moved to Ten Backward.",
    "Dimensional Transducer Destroyed.  Unsure what it did though.",
    "Kitchen staff staging mutiny on Deck 11.",
    "Kindergarden damaged, all children moved to Weapons Storage.",
    "Paint Scratched on Deck 3.",
    "Recursion Field Breach detected in Recursion Field Breach detected in Recursion Field Breach detected in Recursion Field Breach detected...",
    "Transmission Fluid Leak on Deck 4.",
    "Windshield Wipers Damaged.",
    "Tap-Dance Studio Destroyed",
    "Ship's Wifi has gone Offline!"
]